### ISSUE TITLE
ANR if certificate mismatch occurs

### ISSUE THREAD

**Issue by keith30xi** [Appboy/appboy-android-sdk#80] opened 2017-07-12 13:41 UTC
* [X] I have checked [Appboy's documentation](https://www.appboy.com/documentation/Android/) and am still experiencing the issue.

# Report

## What version of the Appboy Android SDK are you using?
2.0.4

## What did you do?
Emulator running app with dev appboy.  On one of our screens, I clicked the back button.  The previous screen should have instantly displayed.  Instead, the UI froze, eventually I received an ANR.  The issue is that my emulator was set to a different date (for testing purposes), a date that happens to be before the valid certificate date for https://dev.appboy.com/

It keeps retrying over and over and eventually ANRed.  

## What did you expect to happen?

Our app screen should have loaded and no ANR in Appboy code.

## What happened instead?

ANR 

## Steps to reproduce

1. Ensure you are using https://dev.appboy.com/api/v3/data
2. Launch the app.
3. In device settings I changed the timestamp to be before the certificate date (e.g., Certificate not valid until Wed Jul 12 04:01:05 EDT 2017) so my date was set to the day before (Tue Jul 11 01:25:56 EDT 2017)
4. See the ANR  AppboyDataSyncService to ANR after repeatedly trying to perform a sync.

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

Not that we are aware of.

It seems like there is a code path that can happen on activity pause where it may block waiting for AppBoyDataSyncService to finish its work (or perhaps something else that is synchronized inside of it). 

## Project that demonstrates the issue

This is a log showing the sync attempting and then eventually the ANR.

[appboyanr.txt](https://github.com/Appboy/appboy-android-sdk/files/1142141/appboyanr.txt)

**Comment by Bucimis** [comment] 2017-07-12 16:32
Hi @keith30xi,

Thanks for filing the issue. We've been able to reproduce the chain validation failure but not the ANR, despite starting the AppboyDataSyncService repeatedly.  AppboyDataSyncService performs all of its useful work in `onHandleIntent()` on a background thread with a background thread priority and could be spuriously identified as the ANR cause here (which could happen e.g. if the app was slow and continued execution before the process was instructed to dumped its ANR stacktrace).

A few followups:

How many times was the ANR seen and how easy is the ANR to repro?  Is it possible to repro with the device time set to today or only when the certificate validation fails?  What device was used to repro?  Any extra information to help us repro would be great.

Thanks,
Appboy Android Team

**Comment by keith30xi** [comment] 2017-07-13 19:19
I have managed to see the ANR 3 times during testing in the last 2 days.  Yesterday it was seemed to be related to the emulator having a date that was before the valid certificate date.  Today I had another ANR in the AppboyDataSyncService due to a timeout on a call.  It proceeded to crash the app and resulted in a relaunch prompt.  

```
07-13 15:10:17.251 1551-1564/? W/ActivityManager: Timeout executing service: ServiceRecord{98acdce u0 com.abercrombie.abercrombie.debug/com.appboy.services.AppboyDataSyncService}
07-13 15:10:18.128 1551-1564/? E/ActivityManager: ANR in com.abercrombie.abercrombie.debug
                                                  PID: 12693
                                                  Reason: executing service com.abercrombie.abercrombie.debug/com.appboy.services.AppboyDataSyncService
                                                  Load: 0.28 / 0.41 / 0.28
                                                  CPU usage from 319942ms to 0ms ago (2017-07-13 15:04:57.310 to 2017-07-13 15:10:17.252):
                                                    9% 12693/com.abercrombie.abercrombie.debug: 5.1% user + 3.9% kernel / faults: 92422 minor 58 major
                                                    8.2% 1820/adbd: 0.8% user + 7.4% kernel / faults: 309353 minor
                                                    3.9% 1273/surfaceflinger: 0.5% user + 3.4% kernel / faults: 4 minor
                                                    2.9% 1551/system_server: 1.3% user + 1.5% kernel / faults: 79794 minor
                                                    0.8% 1318/audioserver: 0% user + 0.7% kernel / faults: 28 minor
                                                    0.4% 2238/com.google.android.gms: 0.2% user + 0.1% kernel / faults: 1905 minor
                                                    0.3% 1919/com.google.android.gms.persistent: 0.2% user + 0.1% kernel / faults: 3544 minor
                                                    0.1% 1747/com.android.phone: 0% user + 0.1% kernel / faults: 57 minor
                                                    0% 1629/com.android.systemui: 0% user + 0% kernel / faults: 182 minor 2 major
                                                    0% 1212/kworker/0:1H: 0% user + 0% kernel
                                                    0% 1298/dmcrypt_write: 0% user + 0% kernel
                                                    0% 1219/logd: 0% user + 0% kernel / faults: 56 minor
                                                    0% 5681/logcat: 0% user + 0% kernel
                                                    0% 8/rcu_preempt: 0% user + 0% kernel
                                                    0% 1999/com.android.launcher3: 0% user + 0% kernel / faults: 613 minor
                                                    0% 5054/kworker/u5:1: 0% user + 0% kernel
                                                    0% 1311/jbd2/dm-0-8: 0% user + 0% kernel
                                                    0% 1623/com.android.inputmethod.latin: 0% user + 0% kernel / faults: 1116 minor
                                                    0% 8676/kworker/u5:2: 0% user + 0% kernel
                                                    0% 3/ksoftirqd/0: 0% user + 0% kernel
                                                    0% 13/kworker/1:0: 0% user + 0% kernel
                                                    0% 12531/kworker/0:1: 0% user + 0% kernel
                                                    0% 2378/com.android.vending: 0% user + 0% kernel / faults: 71 minor
                                                    0% 11/migration/1: 0% user + 0% kernel
                                                    0% 5141/com.google.android.googlequicksearchbox:search: 0% user + 0% kernel / faults: 599 minor
                                                    0% 1270/lmkd: 0% user + 0% kernel
                                                    0% 12/ksoftirqd/1: 0% user + 0% kernel
                                                    0% 1327/netd: 0% user + 0% kernel / faults: 398 minor
                                                    0% 1882/android.process.acore: 0% user + 0% kernel / faults: 3 minor
                                                    0% 12522/kworker/1:1: 0% user + 0% kernel
                                                    0% 1267/healthd: 0% user + 0% kernel
                                                    0% 1272/servicemanager: 0% user + 0% kernel
                                                    0% 16/kworker/u4:1: 0% user + 0% kernel
                                                    0% 1328/rild: 0% user + 0% kernel
                                                    0% 1979/com.google.process.gapps: 0% user + 0% kernel / faults: 252 minor
                                                    0% 4991/kworker/0:0: 0% user + 0% kernel
                                                    0% 5060/com.android.gallery3d: 0% user + 0% kernel / faults: 39 minor
                                                    0% 6/kworker/u4:0: 0% user + 0% kernel
                                                    0% 7/migration/0: 0% user + 0% kernel
                                                    0% 556/kswapd0: 0% user + 0% kernel
                                                    0% 905/ueventd: 0% user + 0% kernel
                                                    0% 1321/installd: 0% user + 0% kernel / faults: 37 minor
                                                    0% 4996/com.android.defcontainer: 0% user + 0% kernel / faults: 308 minor
                                                    0% 5076/com.android.printspooler: 0% user + 0% kernel / faults: 138 minor
                                                    0% 5092/com.android.keychain: 0% user + 0% kernel / faults: 40 minor
                                                    0% 5176/com.android.documentsui: 0% user + 0% kernel / faults: 29 minor
                                                    0% 5359/com.google.android.partnersetup: 0% user + 0% kernel / faults: 19 minor
                                                    0% 12657/com.google.android.apps.photos: 0% user + 0% kernel / faults: 61 minor
                                                   +0% 13067/kworker/u5:0: 0% user + 0% kernel
                                                   +0% 13903/com.google.android.talk: 0% user + 0% kernel
                                                   +0% 14164/com.google.android.talk:matchstick: 0% user + 0% kernel
                                                  15% TOTAL: 5.2% user + 9.2% kernel + 0% iowait + 0.5% softirq
                                                  CPU usage from 337ms to 843ms later (2017-07-13 15:10:17.589 to 2017-07-13 15:10:18.095):
                                                    7.1% 1820/adbd: 1.7% user + 5.3% kernel / faults: 291 minor
                                                      5.3% 1825/->host-9: 0% user + 5.3% kernel
                                                      1.7% 1820/adbd: 1.7% user + 0% kernel
                                                      1.7% 1826/<-host-9: 0% user + 1.7% kernel
                                                    3.8% 1551/system_server: 1.9% user + 1.9% kernel
                                                      3.8% 1564/ActivityManager: 0% user + 3.8% kernel
                                                  5.1% TOTAL: 3% user + 1% kernel + 1% softirq
```

**Comment by Bucimis** [comment] 2017-07-13 21:17
Hi @keith30xi,

Thanks for following up.  To help confirm that `AppboyDataSyncService` is causing ANRs, could you check whether its still possible to induce an ANR with automatic appboy data syncing turned off?  To do this, turn off automatic data flushing in your `appboy.xml`:

```
  <integer name="com_appboy_data_flush_interval_bad_network">-1</integer>
  <integer name="com_appboy_data_flush_interval_good_network">-1</integer>
  <integer name="com_appboy_data_flush_interval_great_network">-1</integer>
```

With automatic data syncing turned off, `AppboyDataSyncService` will never be instantiated.

Also, it would help us debug if we had access to a sample app with verbose Appboy logging enabled (see https://www.appboy.com/documentation/Android/#verbose-logging) and repro instructions.  Feel free to reach out to android@appboy.com with these materials and we'll continue debugging on our end.

Thanks again,
Appboy Android Team

**Comment by keith30xi** [comment] 2017-07-19 15:09
Understood.  It is very challenging to reproduce this issue so we will continue to monitor.   Do you know if there is a way to turn off the ssl certificate validations for dev environments.  The SSL cert at https://dev.appboy.com/api/v3/data seems to keep updating and we do lots of testing by having to change dates around (to test for specific scenarios).

**Comment by Bucimis** [comment] 2017-08-01 17:47
Hi @keith30xi,

Were there any further issues with ANRs or SSL on your end?  Let us know, we'd like to close this issue out if possible.

Regards,
Appboy Android Team

**Comment by vhuynh** [comment] 2017-09-23 01:02
I ran into this same issue, caused by com.appboy.services.AppboyDataSyncService. Once it occurs, I get an ANR on **every** launch. Once I cleared the data, I could no longer reproduce it. Not sure if its related to "certificates". 

Nexus 6 on 6.0, using Appboy v2.0.4

**Comment by Bucimis** [comment] 2017-09-25 20:25
@vhuynh 

Thanks for reaching out.  Would you happen to have a stacktrace or crash report available, as well as steps to repro?

As mentioned earlier in the thread, if automatic Appboy data syncs are turned off, do you still get ANRs from AppboyDataSyncService?  (See https://github.com/Appboy/appboy-android-sdk/issues/80#issuecomment-315205009 for instructions)

Thanks,
Jared

**Comment by vhuynh** [comment] 2017-09-25 20:43
Edge case and not reproducible after clearing data. I only posted to point out that Keith was not the only one. All I have is similar to what he posted. Hope it helps:

> 09-22 15:02:21.285 856-869/? E/ActivityManager: ANR in  ***.***.***
                                                PID: 13055
                                                Reason: executing service ***.***.***/com.appboy.services.AppboyDataSyncService
                                                Load: 12.83 / 12.78 / 12.31
                                                CPU usage from 101115ms to 0ms ago:
                                                  7.2% 277/surfaceflinger: 3.4% user + 3.7% kernel / faults: 130 minor
                                                  5% 856/system_server: 2.8% user + 2.2% kernel / faults: 9671 minor 11 major
                                                  3.2% 2116/com.google.android.gms.persistent: 2.7% user + 0.4% kernel / faults: 8422 minor 9 major
                                                  2.5% 334/mdss_fb0: 0% user + 2.5% kernel
                                                  1.4% 1520/com.android.systemui: 0.9% user + 0.5% kernel / faults: 6728 minor 4 major
                                                  1% 11471/kworker/u8:6: 0% user + 1% kernel
                                                  0.9% 24113/kworker/u8:8: 0% user + 0.9% kernel
                                                  0.9% 11927/kworker/u8:2: 0% user + 0.9% kernel
                                                  0.8% 13915/com.google.android.googlequicksearchbox:search: 0.5% user + 0.2% kernel / faults: 7167 minor
                                                  0.7% 4265/com.zingbox.manga.entertain: 0.6% user + 0.1% kernel / faults: 1691 minor 1 major
                                                  0.7% 12435/kworker/u8:9: 0% user + 0.7% kernel
                                                  0.7% 208/mmcqd/0: 0% user + 0.7% kernel
                                                  0.4% 112/kswapd0: 0% user + 0.4% kernel
                                                  0.5% 20205/kworker/u8:4: 0% user + 0.5% kernel
                                                  0.4% 193/irq/33-bw_hwmon: 0% user + 0.4% kernel
                                                  0.4% 1886/com.google.android.googlequicksearchbox: 0.3% user + 0.1% kernel / faults: 3589 minor
                                                  0.3% 24637/com.android.chrome: 0.2% user + 0.1% kernel / faults: 1036 minor
                                                  0.3% 30/kworker/u9:0: 0% user + 0.3% kernel
                                                  0.3% 1918/com.google.android.gms: 0.2% user + 0% kernel / faults: 879 minor
                                                  0.3% 172/cfinteractive: 0% user + 0.3% kernel
                                                  0.3% 279/sensors.qcom: 0.1% user + 0.1% kernel / faults: 70 minor
                                                  0.2% 11996/kworker/0:2: 0% user + 0.2% kernel
                                                  0.2% 8/rcu_preempt: 0% user + 0.2% kernel
                                                  0.2% 1811/com.google.android.inputmethod.korean: 0.1% user + 0% kernel / faults: 2842 minor
                                                  0.2% 366/adbd: 0% user + 0.1% kernel / faults: 248 minor
                                                  0.2% 9356/kworker/0:3: 0% user + 0.2% kernel
                                                  0.1% 9620/kworker/1:2H: 0% user + 0.1% kernel
                                                  0.1% 249/logd: 0% user + 0% kernel / faults: 69 minor
                                                  0.1% 11964/kworker/u8:5: 0% user + 0.1% kernel
                                                  0.1% 5692/kworker/2:2H: 0% user + 0.1% kernel
                                                  0.1% 12396/kworker/0:2H: 0% user + 0.1% kernel
                                                  0.1% 20822/kworker/3:2H: 0% user + 0.1% kernel
                                                  0.1% 3/ksoftirqd/0: 0% user + 0.1% kernel
                                                  0.1% 375/mediaserver: 0% user + 0.1% kernel / faults: 276 minor
                                                  0.1% 43/system: 0% user + 0.1% kernel
                                                  0.1% 215/irq/163-dwc3: 0% user + 0.1% kernel
                                                  0.1% 10112/logcat: 0% user + 0% kernel / faults: 39 minor
                                                  0% 135/mdss_dsi_event: 0% user + 0% kernel
                                                  0% 1869/com.android.phone: 0% user + 0% kernel / faults: 465 minor
                                                  0% 10872/wpa_supplicant: 0% user + 0% kernel / faults: 47 minor
                                                  0% 11864/kworker/1:0: 0% user + 0% kernel
                                                  0% 12/ksoftirqd/1: 0% user + 0% kernel
                                                  0% 16/ksoftirqd/2: 0% user + 0% kernel
                                                  0% 20/ksoftirqd/3: 0% user + 0% kernel
                                                  0% 1840/com.quicinc.cne.CNEService: 0% user + 0% kernel / faults: 217 minor
                                                  0% 166/irq/439-atmel_m: 0% user + 0% kernel
                                                  0% 356/dmcrypt_write: 0% user + 0% kernel
                                                  0% 363/jbd2/dm-1-8: 0% user + 0% kernel
                                                  0% 11848/kworker/2:0: 0% user + 0% kernel
                                                  0% 388/zygote: 0% user + 0% kernel / faults: 3808 minor
                                                  0% 9803/com.android.chrome:sandboxed_process1: 0% user + 0% kernel / faults: 295 minor
                                                  0% 9877/kworker/0:0H: 0% user + 0% kernel
                                                  0% 275/lmkd: 0% user + 0% kernel / faults: 20 minor
                                                  0% 276/servicemanager: 0% user + 0% kernel / faults: 42 minor
                                                  0% 384/mpdecision: 0% user + 0% kernel / faults: 31 minor
                                                  0% 3196/com.android.vending: 0% user + 0% kernel / faults: 1249 minor 12 major
                                                  0% 11137/kworker/3:2: 0% user + 0% kernel
                                                  0% 385/thermal-engine: 0% user + 0% kernel / faults: 27 minor
                                                  0% 25742/com.android.settings: 0% user + 0% kernel / faults: 102 minor
                                                  0% 383/adspd: 0% user + 0% kernel / faults: 29 minor
                                                  0% 9717/com.android.chrome:privileged_process0: 0% user + 0% kernel / faults: 35 minor
                                                  0% 20460/com.gamebench.metricscollector: 0% user + 0% kernel / faults: 35 minor
                                                  0% 224/wl_event_handle: 0% user + 0% kernel
                                                  0% 274/healthd: 0% user + 0% kernel
                                                  0% 371/netd: 0% user + 0% kernel / faults: 129 minor
                                                  0% 373/rild: 0% user + 0% kernel / faults: 98 minor
                                                  0% 380/
09-22 15:02:43.379 856-869/? W/ActivityManager: Timeout executing service: ServiceRecord{245de25 u0 com.ebates.dev/com.appboy.services.AppboyDataSyncService}

**Comment by Bucimis** [comment] 2017-09-25 21:34
@vhuynh sounds good, thanks for this additional data point.

To add more context to https://github.com/Appboy/appboy-android-sdk/issues/80#issuecomment-314824705, `AppboyDataSyncService` doesn't override `onStart` or `onCreate`, so any work done on the main thread to instantiate the service is already minimized to the extent possible.

This is good signal for us to start investigating ways of migrating off `IntentService` altogether, but in the short term, we will probably keep observing the issue.  

Let us know if that works for you,
Appboy Android Team

**Comment by radixdev** [comment] 2017-12-22 18:20
Hey @vhuynh & @keith30xi ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.

**Closed by radixdev** 2017-12-22 18:20 UTC
