### ISSUE TITLE
SDK doesn't update language in dashboard

### ISSUE THREAD

**Issue by rigo-ptz** [Appboy/appboy-android-sdk#142] opened 2019-10-17 13:18 UTC
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?

3.6.0

## What did you do?
I integrated Braze as follow:
```
registerActivityLifecycleCallbacks(
      AppboyLifecycleCallbackListener(true, true)
    )
    val appboyConfig = AppboyConfig
      .Builder()
      .setDefaultNotificationChannelName(
        getString(NotificationUtil.WhimNotificationChannel.OTHER.nameId)
      )
    Appboy.configure(this, appboyConfig.build())
    Appboy.getInstance(this).appboyImageLoader = GlideBrazeImageLoader()
    if (BuildConfig.DEBUG) AppboyLogger.setLogLevel(Log.WARN)
```
Then I tried to change device's language from English to Finnish.

## What did you expect to happen?

I expected to see new language on the dashboard.

## What happened instead?

There were previous language and locale.

![image](https://user-images.githubusercontent.com/8643656/67012037-5e3ba180-f0f9-11e9-9c55-405a6fb314cd.png)

But the same scenario works on iOS device.

**Comment by radixdev** [comment] 2019-10-17 20:36
I can't reproduce.

The original locale for this user was `en_US` then later updated after I changed to `Suomi` in the android language settings.
![image](https://user-images.githubusercontent.com/2373546/67045198-cb503680-f0fb-11e9-9c52-c8667af672d8.png)

The SDK sends up the locale update successfully
![image](https://user-images.githubusercontent.com/2373546/67045246-e4f17e00-f0fb-11e9-807c-352acd45cfc5.png)

Please reply with the following:
1. Exact steps on how to reproduce `Then I tried to change device's language from English to Finnish.`
2. The device model, OS, and emulator status
3. Other customizations done to the SDK

**Comment by rigo-ptz** [comment] 2019-10-18 08:37
Thank you for the reply.
Steps:
1. Remove app data from Settings
2. Launch the app
3. I'm testing it with AS Emulator.
 “device”: {
       “os_version”: “28",
       “carrier”: “Android”,
       “model”: “Android SDK built for x86",
       “resolution”: “1080x1794",
       “locale”: “en_US”,
       “remote_notification_enabled”: true,
       “android_is_background_restricted”: false,
       “time_zone”: “Europe\/Helsinki”
     },
4. Kill the app
5. Change language in device's Settings
6.
 "device": {
        "locale": "fi_FI"
      },
7. 
![image](https://user-images.githubusercontent.com/8643656/67078790-ad85de80-f19a-11e9-909b-80f553bd6a18.png)

8. I have custom view styles for in-app messages, but it shouldn't influence on library behavior.

**Comment by rigo-ptz** [comment] 2019-10-18 09:07
For me it works only in this order:
1. Kill the app
2. Clear app data
3. Change language
4. Start the app

**Comment by radixdev** [comment] 2019-10-21 19:25
Hi @rigo-ptz ,

I still cannot reproduce with your steps. Is it possible you're not calling `changeUser()` after you log back into the app? The SDK cannot retain user data across app data wipes so it's possible that the locale change data wasn't attributed to the same user as before. 

Can you provide complete [verbose logging](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration/#braze-log-level) of every step of your repro?

**Comment by radixdev** [comment] 2019-11-12 18:32
Hey @rigo-ptz ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.

**Closed by radixdev** 2019-11-12 18:32 UTC
