### ISSUE TITLE
Dismissing Push notification from notification area freezes device

### ISSUE THREAD

**Issue by amit3vedi** [Appboy/appboy-android-sdk#180] opened 2021-04-05 05:51 UTC
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?
13.1.0

## What did you do?

Dismissing push notification from notification area

## What did you expect to happen?

Notification should dismiss without any issue

## What happened instead?

whenever dismiss notification device freezes. most probably issue is with newly added `NotificationTrampolineActivity` this activity starts and does not close. and this activity is transparent that's why it seems like device is freeze but actually this activity is receiving all touches. untill user manually goto recent apps and close entire App.

## Steps to reproduce

- Upgrade Braze android SDK to 13.1.0
- Receive push on device (i'm using Samsung S8 Android version 9.0) 
- Dismiss push notification from notification area
- Device Hangs and user can not do anything
- goto recent app screen and close application
- Device start working fine

## Project that demonstrates the issue

# ANR Reporting

## Braze Related Threads In ANR

This is a very critical issue and our users are currently facing this freezing issue please fix this ASAP. and if possible mark this kind of release as alpha or beta instead of stable release.

**Comment by radixdev** [comment] 2021-04-05 16:57
Hi @amit3vedi ,

We're investigating this issue and should have a fix/response very shortly.

**Comment by radixdev** [comment] 2021-04-05 17:16
Hi @amit3vedi ,

We've confirmed this issue and will have a fix release very shortly. I will update this thread once it's released.

**Comment by radixdev** [comment] 2021-04-05 18:45
Hi @amit3vedi ,

A bugfix has been released in version 13.1.1 of the SDK to address this issue.

**Comment by amit3vedi** [comment] 2021-04-06 05:53
@radixdev notification dismiss issue is fixed in 13.1.1 device is not freezing whenever i dismiss push notification but issue still exists whenever i click on push notification device freezes again on 13.1.1. i'm using Samsung S8 android 9.0

**Comment by radixdev** [comment] 2021-04-06 16:01
Can you provide reproduction steps (like in your first post)? I cannot reproduce after clicking on a push. Can you also provide [verbose logging](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration/) of this happening?

**Comment by radixdev** [comment] 2021-04-06 20:33
Can you update to 13.1.2 and see if this fixes your issue? We identified and fixed an issue with the lifecycle management of the `NotificationTrampolineActivity` class in the latest release that likely fixes the click issue you identified.

**Comment by amit3vedi** [comment] 2021-04-08 15:00
@radixdev this issue seems to have resolved in 13.1.2. Thank you

**Comment by radixdev** [comment] 2021-04-08 15:02
Thank you for filing!

**Closed by radixdev** 2021-04-08 15:02 UTC
