### ISSUE TITLE
Issue with proguard optimization and code shrinking

### ISSUE THREAD

**Issue by beaverlyhills** [Appboy/appboy-android-sdk#49] opened 2016-03-02 21:06 UTC
Hello,
We're having issues obfuscating our project with Appboy Android SDK:

> Removing unused program classes and class elements...
>   Original number of program classes: 8648
>   Final number of program classes:    7011
> Optimizing...
> Unexpected error while evaluating instruction:
>   Class       = [com/braintreepayments/api/AndroidPay]
>   Method      = [getConnectedApiClient(Landroid/content/Context;)Lcom/google/android/gms/common/api/GoogleApiClient;]
>   Instruction = [13] invokespecial #53
>   Exception   = [java.lang.IllegalArgumentException](Can't find common super class of [android/content/Context] %28with 2 known super classes%29 and [com/appboy/services/AppboyWearableListenerService] %28with 1 known super classes%29)
> Unexpected error while performing partial evaluation:
>   Class       = [com/braintreepayments/api/AndroidPay]
>   Method      = [getConnectedApiClient(Landroid/content/Context;)Lcom/google/android/gms/common/api/GoogleApiClient;]
>   Exception   = [java.lang.IllegalArgumentException](Can't find common super class of [android/content/Context] %28with 2 known super classes%29 and [com/appboy/services/AppboyWearableListenerService] %28with 1 known super classes%29)
> Warning: Exception while processing task java.io.IOException: java.lang.IllegalArgumentException: Can't find common super class of [android/content/Context](with 2 known super classes) and [com/appboy/services/AppboyWearableListenerService](with 1 known super classes)

Error message is quite confusing, but eventually I was able to find workaround by adding play-services-wearable dependency to your project:

> dependencies
>  {
>     // ...
>     compile 'com.google.android.gms:play-services-ads:8.4.0'
>     compile 'com.google.android.gms:play-services-gcm:8.4.0'
>     compile 'com.google.android.gms:play-services-wearable:8.4.0'
>     compile 'com.appboy:android-sdk-ui:1.13.+'
> }`

**Comment by briancaw** [comment] 2016-03-03 01:20
Hi @beaverlyhills 

We're actively investigating this issue for you and will respond with our findings ASAP (we'll update the status tomorrow once we've been able to do some investigation).

Thanks,
Brian

**Comment by Bucimis** [comment] 2016-03-03 07:30
Hi @beaverlyhills

We were able to repro.  Do you have proguard optimization turned on?  Please try adding `-dontoptimize` to your proguard configuration. That fixed the error in our repro case.

If you haven't, you may consider adding the default android proguard file from the android sdk to your proguard configuration. You can do this with a line in your `build.gradle` like:

`proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'` (the second file is the path to your own custom proguard file)

The default android proguard file also turns off optimization with the following reasoning:

# Optimization is turned off by default. Dex does not like code run
# through the ProGuard optimize and preverify steps (and performs some
# of these optimizations on its own).
# Note that if you want to enable optimization, you cannot just
# include optimization flags in your own project configuration file;
# instead you will need to point to the
# "proguard-android-optimize.txt" file instead of this one from your
# project.properties file.

Please let us know if this solves your issue.  If not, if you could send over your proguard configuration and proguard statements in build.gradle, that would help us get down to the bottom of things faster.  

Thanks,
Jared

**Comment by Bucimis** [comment] 2016-03-17 16:03
Hi @beaverlyhills 

Were you able to resolve the issue on your end?

Thanks,
Jared

**Comment by Bucimis** [comment] 2016-04-05 22:39
Hi @beaverlyhills,

Going to close this issue for now.  Feel free to re-open if the issue is unresolved at your end.

Thanks,
Jared

**Comment by AamirAbro** [comment] 2018-02-19 12:22
@Bucimis We are using "proguard-android-optimize.txt" and seeing similar issue.
```
Unexpected error while shrinking instructions after partial evaluation:
  Class       = [com/appboy/ui/inappmessage/jsinterface/AppboyInAppMessageHtmlJavascriptInterface]
  Method      = [parseProperties(Ljava/lang/String;)Lcom/appboy/models/outgoing/AppboyProperties;]
  Exception   = [java.lang.ArrayIndexOutOfBoundsException] (null)
```

**Comment by Bucimis** [comment] 2018-02-20 18:49
re-opening to track

**Comment by radixdev** [comment] 2018-02-20 18:58
Hello @AamirAbro ,

We cannot reproduce the proguard error you're seeing with "proguard-android-optimize.txt". For reference, here is our gradle used to reproduce:

```gradle
minifyEnabled true
proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
```

1. What is your proguard configuration?
2. What version of the SDK are you using?

Thanks,
Braze Mobile Team

**Comment by Bucimis** [comment] 2018-03-09 23:16
Hey @AamirAbro, were you able to solve the issue?

**Comment by radixdev** [comment] 2018-03-19 15:54
Hey @AamirAbro ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.

**Closed by radixdev** 2018-03-19 15:54 UTC

**Comment by AamirAbro** [comment] 2018-04-05 10:07
Sorry I have missed to update here.

And yes we are still seeing this error in the proguard logs.
we are currently on `3.1.0` and have added the following rules for apptimize

```
-keep class com.apptimize.** { *; }
-keepclassmembers class * extends com.apptimize.ApptimizeTest {
  <methods>;
}
#https://apptimize.com/docs/installation/android-installation.html#initializing-apptimize Step 4
-keep class com.mixpanel.android.mpmetrics.MixpanelAPI { *; }
-keep class com.google.android.gms.analytics.Tracker { *; }
-keep class com.google.analytics.tracking.android.Tracker { *; }
```

**Comment by radixdev** [comment] 2018-04-05 17:12
@AamirAbro Did you mean to file this with the Apptimize team? The Braze SDK does not have a 3.1.0 SDK version.

If not, can you file a new issue or email support@braze.com so we can track this better?

Can you include:
1. The complete proguard config file
2. The complete proguard error log
3. Your proguard setup in gradle

Thanks,
Braze Android Team

**Comment by AamirAbro** [comment] 2018-04-05 18:03
@radixdev sorry about that version and progaurd rules I mixed appboy and apptimize up -- it was a hectic day:) . But error is from appboy/braze will be emailing support. thanks.
