### ISSUE TITLE
attempt to re-open an already-closed object: SQLiteDatabase

### ISSUE THREAD

**Issue by TobiasJonsson** [Appboy/appboy-android-sdk#19] opened 2014-05-15 11:05 UTC
Got an exception in the log during startup of our app. 

We are using the unreleased version 1.3.3 of appboy.

Note: the exception did not crash the app.

05-15 12:39:30.470: W/Appboy.bo.app.bd(28486): java.util.concurrent.ExecutionException: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/com.planeto.quizbattle2.stern/databases/appboy.db.qb2-stern:8001
05-15 12:39:30.470: W/Appboy.bo.app.bd(28486):     at java.util.concurrent.FutureTask.report(FutureTask.java:94)
05-15 12:39:30.470: W/Appboy.bo.app.bd(28486):     at java.util.concurrent.FutureTask.get(FutureTask.java:160)
05-15 12:39:30.470: W/Appboy.bo.app.bd(28486):     at bo.app.bo.trigger(SourceFile:71)
05-15 12:39:30.470: W/Appboy.bo.app.bd(28486):     at bo.app.x.run(SourceFile:246)
05-15 12:39:30.470: W/Appboy.bo.app.bd(28486):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
05-15 12:39:30.470: W/Appboy.bo.app.bd(28486):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
05-15 12:39:30.470: W/Appboy.bo.app.bd(28486):     at java.lang.Thread.run(Thread.java:841)
05-15 12:39:30.470: W/Appboy.bo.app.bd(28486): Caused by: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/com.planeto.quizbattle2.stern/databases/appboy.db.qb2-stern:8001
05-15 12:39:30.470: W/Appboy.bo.app.bd(28486):     at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
05-15 12:39:30.470: W/Appboy.bo.app.bd(28486):     at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1492)
05-15 12:39:30.470: W/Appboy.bo.app.bd(28486):     at bo.app.hw.a(SourceFile:134)
05-15 12:39:30.470: W/Appboy.bo.app.bd(28486):     at bo.app.cb.run(SourceFile:70)
05-15 12:39:30.470: W/Appboy.bo.app.bd(28486):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
05-15 12:39:30.470: W/Appboy.bo.app.bd(28486):     at java.util.concurrent.FutureTask.run(FutureTask.java:234)
05-15 12:39:30.470: W/Appboy.bo.app.bd(28486):     ... 3 more

**Comment by Bucimis** [comment] 2016-06-09 23:46
Hi @TobiasJonsson and @Guihgo,

A fix for this bug was included in today's release version 1.13.5. If you could update to this release and confirm the issue is resolved it would be much appreciated.

Thanks,
Appboy Android Team

**Comment by Guihgo** [comment] 2016-06-10 19:24
Thanks ! 100% working

**Comment by briancaw** [comment] 2016-06-10 19:26
Thanks very much for confirming @Guihgo.  @TobiasJonsson thanks for originally reporting and if you find the error persists, please reopen this issue.

**Closed by briancaw** 2016-06-10 19:26 UTC
