### ISSUE TITLE
Requesting immediate data flush to Braze constantly in logcat with screen off. [Bug]: 

### ISSUE THREAD

**Issue by Ausiguy** [Appboy/appboy-android-sdk#260] opened 2023-03-02 17:20 UTC
### Braze Android SDK Version

24.2.0

### Steps To Reproduce

With Braze setup and working fine on Android I minimize the app by pressing the Home button. I have the device connected via USB to Android Studio and I'm monitoring logcat. I see the following messages appearing at regular intervals (e very 30 seconds) and they never stop. This is with the device screen completely off. FYI, I have purposely obfuscated the package name in these logs.

So, is this expected behavior? It seems like it's doing some network request and it's certainly using CPU and battery. Not great when the device has the screen off. It continues until the app is removed from recents.

See below this first log for a detailed log that is observed when BrazeLogger.logLevel = Log.VERBOSE

I don't believe that our app is doing anything in the background to trigger this but I could be wrong. If anyone knows how to stop this from happening that would be great.

### Expected Behavior

I don't believe that Braze should be constantly doing anything in the background when the device screen is off.

### Actual Incorrect Behavior

Braze is constantly doing something in the background when the device screen is off. If there is something that the app is doing that is triggering this, or perhaps something that the app is not doing when it's paused in order to stop this can someone please provide details on what needs to be done to resolve this. Thanks.

### Verbose Logs

```shell
2023-03-02 10:49:07.856  7985-8068  Braze v24.2.0 .Braze    com.xxxxx.xxxxxx              I  Requesting immediate data flush to Braze.
2023-03-02 10:49:27.796  7985-8068  Braze v24.2.0 .Braze    com.xxxxx.xxxxxx              I  Requesting immediate data flush to Braze.
2023-03-02 10:49:57.797  7985-8068  Braze v24.2.0 .Braze    com.xxxxx.xxxxxx              I  Requesting immediate data flush to Braze.
2023-03-02 10:50:27.802  7985-8068  Braze v24.2.0 .Braze    com.xxxxx.xxxxxx              I  Requesting immediate data flush to Braze.
2023-03-02 10:50:57.806  7985-8068  Braze v24.2.0 .Braze    com.xxxxx.xxxxxx              I  Requesting immediate data flush to Braze.
2023-03-02 10:51:27.810  7985-8068  Braze v24.2.0 .Braze    com.xxxxx.xxxxxx              I  Requesting immediate data flush to Braze.
2023-03-02 10:51:57.813  7985-8068  Braze v24.2.0 .Braze    com.xxxxx.xxxxxx              I  Requesting immediate data flush to Braze.
2023-03-02 10:52:27.816  7985-8068  Braze v24.2.0 .Braze    com.xxxxx.xxxxxx              I  Requesting immediate data flush to Braze.
2023-03-02 10:52:57.818  7985-8068  Braze v24.2.0 .Braze    com.xxxxx.xxxxxx              I  Requesting immediate data flush to Braze.
2023-03-02 10:53:27.820  7985-8068  Braze v24.2.0 .Braze    com.xxxxx.xxxxxx              I  Requesting immediate data flush to Braze.
2023-03-02 10:53:57.824  7985-8068  Braze v24.2.0 .Braze    com.xxxxx.xxxxxx              I  Requesting immediate data flush to Braze.
2023-03-02 10:54:27.827  7985-8068  Braze v24.2.0 .Braze    com.xxxxx.xxxxxx              I  Requesting immediate data flush to Braze.
2023-03-02 10:54:57.831  7985-8068  Braze v24.2.0 .Braze    com.xxxxx.xxxxxx              I  Requesting immediate data flush to Braze.


With logging set to VERBOSE:



2023-03-02 11:13:33.392 13339-13381 Braze v24....eCoroutine com.xxxxx.xxxxxx              V  Requesting data flush from automatic sync policy
2023-03-02 11:13:33.395 13339-13409 Braze v24.2.0 .Braze    com.xxxxx.xxxxxx              I  Requesting immediate data flush to Braze.
2023-03-02 11:13:33.402 13339-13409 Braze v24.2.0 .a1       com.xxxxx.xxxxxx              D  bo.app.p0 fired:             commandType = ADD_REQUEST
                                                                                                                brazeEvent = null
                                                                                                                sessionId = null
                                                                                                                brazeRequest = {
                                                                                                      "respond_with": {
                                                                                                        "user_id": "442fcd6c-a3aa-4a1f-92ca-2ed36d1747ad",
                                                                                                        "config": {
                                                                                                          "config_time": 1677174225
                                                                                                        }
                                                                                                      }
                                                                                                    }
                                                                                                    to target: https://sdk.iad-01.braze.com/api/v3/data
2023-03-02 11:13:33.402 13339-13409 Braze v24.2.0 .a1       com.xxxxx.xxxxxx              D  Triggering bo.app.p0 on 1 subscribers.
2023-03-02 11:13:33.404 13339-13409 Braze v24.2.0 .r0       com.xxxxx.xxxxxx              V  Added request to dispatcher with parameters: 
                                                                                                    {
                                                                                                      "respond_with": {
                                                                                                        "user_id": "442fcd6c-a3aa-4a1f-92ca-2ed36d1747ad",
                                                                                                        "config": {
                                                                                                          "config_time": 1677174225
                                                                                                        }
                                                                                                      }
                                                                                                    }
2023-03-02 11:13:33.404 13339-13380 Braze v24.2.0 .r0       com.xxxxx.xxxxxx              V  SDK Auth is disabled, not adding signature to request
2023-03-02 11:13:33.409 13339-13380 Braze v24.2.0 .l0       com.xxxxx.xxxxxx              D  Cache locked successfully for export: bo.app.l0@a9982c7
2023-03-02 11:13:33.410 13339-13380 Braze v24.2.0 .m6       com.xxxxx.xxxxxx              D  Cache locked successfully for export: bo.app.m6@61f80f4
2023-03-02 11:13:33.412 13339-13380 Braze v24.2.0 .t0       com.xxxxx.xxxxxx              D  Short circuiting execution of network request and immediately marking it as succeeded.
2023-03-02 11:13:33.413 13339-13380 Braze v24.2.0 .j0       com.xxxxx.xxxxxx              D  DataSyncRequest executed successfully.
2023-03-02 11:13:33.414 13339-13380 Braze v24.2.0 .a1       com.xxxxx.xxxxxx              D  bo.app.s0 fired: DispatchSucceededEvent(request={
                                                                                                      "device_id": "c85fbe42-1615-44a5-97ca-002d201441a2",
                                                                                                      "time": 1677777213,
                                                                                                      "api_key": "6c492f20-99c9-496b-87cb-326cf2cdc57d",
                                                                                                      "sdk_version": "24.2.0",
                                                                                                      "app_version": "3.0.0",
                                                                                                      "app_version_code": "46.0.0.0",
                                                                                                      "respond_with": {
                                                                                                        "user_id": "442fcd6c-a3aa-4a1f-92ca-2ed36d1747ad",
                                                                                                        "config": {
                                                                                                          "config_time": 1677174225
                                                                                                        }
                                                                                                      }
                                                                                                    }
                                                                                                    to target: https://sdk.iad-01.braze.com/api/v3/data)
2023-03-02 11:13:33.414 13339-13380 Braze v24.2.0 .a1       com.xxxxx.xxxxxx              D  Triggering bo.app.s0 on 1 subscribers.
2023-03-02 11:13:33.415 13339-13380 Braze v24.2.0 .l0       com.xxxxx.xxxxxx              V  Notifying confirmAndUnlock listeners for cache: bo.app.l0@a9982c7
2023-03-02 11:13:33.415 13339-13380 Braze v24.2.0 .m6       com.xxxxx.xxxxxx              V  Notifying confirmAndUnlock listeners for cache: bo.app.m6@61f80f4
2023-03-02 11:13:33.416 13339-13380 Braze v24.2.0 .a5       com.xxxxx.xxxxxx              V  Attempting to unlock server config info.
2023-03-02 11:13:33.416 13339-13380 Braze v24.2.0 .a5       com.xxxxx.xxxxxx              D  Unlocking config info lock.
```

**Comment by radixdev** [comment] 2023-03-02 18:51
Hi @Ausiguy ,

This is expected behavior. The SDK is not actually making any network requests in this state, see the `Short circuiting execution of network request and immediately marking it as succeeded.` log. What the SDK is doing is attempting to make routine network flushes if data is present. However since there's no data to be sent (since the screen is off and nothing is being "done" on the SDK), the requests are being short-circuited and not resulting in any actual network requests. We will keep this in mind and try to make those logs clearer. 
You can also set a automatic longer flush interval via `https://appboy.github.io/appboy-android-sdk/kdoc/braze-android-sdk/com.braze.configuration/-braze-config/-builder/set-great-network-data-flush-interval.html` (and also setBad, setGood) or just set them all `-1` to disable automatic syncs.

**Closed by radixdev** 2023-03-02 18:51 UTC
Labels: bug

**Comment by Ausiguy** [comment] 2023-03-02 19:17
Thanks very much for the clarification. Cheers!
