### ISSUE TITLE
Compatibility with Android O

### ISSUE THREAD

**Issue by StanKocken** [Appboy/appboy-android-sdk#77] opened 2017-06-13 15:48 UTC
We want to push an Android O compatible build but we are blocked by AppBoy notifications.
AppBoy notifications needs to support the "channel". See https://developer.android.com/preview/features/notification-channels.html

I guess the developper will have to create the channel on his side (as we do for our others notifications), but can you give us a method to set the channel id to use for AppBoy?

Thanks for your support.

**Comment by Bucimis** [comment] 2017-06-13 20:23
Hi @StanKocken,

You can use a custom notification factory to set custom fields like notification channel before display.  You'll want to create a class that implements `IAppboyNotificationFactory` and pass an instance to Appboy using `Appboy.setCustomAppboyNotificationFactory();`.

Here's an example of what the `createNotification()` implementation in your `IAppboyNotificationFactory` may look like:

```
  @Override
  public Notification createNotification(AppboyConfigurationProvider appConfigurationProvider,
                                         Context context, Bundle notificationExtras, Bundle appboyExtras) {
    NotificationCompat.Builder notificationBuilder = AppboyNotificationFactory.getInstance().populateNotificationBuilder(appConfigurationProvider, context, notificationExtras, appboyExtras);
    notificationBuilder.setChannelId("my_channel_01");
    return notificationBuilder.build();
  }
```

Check out our full documentation here: https://www.appboy.com/documentation/Android/#customizing-your-integration

Thanks,
Appboy Android Team

**Comment by StanKocken** [comment] 2017-06-14 14:25
Thanks, that will work for me for our release.
Do you want to make it working without having to create a custom notificationFactory in the future?
Be free to close this issue otherwise.

**Comment by Bucimis** [comment] 2017-06-14 14:39
Thanks @StanKocken!

Yep, in the next few months we plan to release a more seamless integration for notification channel and will reach out again when it's available.  

I'll close this issue for now.

**Closed by Bucimis** 2017-06-14 14:39 UTC

**Comment by jazimm** [comment] 2017-12-04 17:53
Hi have you released the new integration for creating the channel ID you mentioned in the last post? Currently I'm using the following to set the notification channel name and description but I don't see a method to set the ID which is required on the Braze dashboard when entering the default Channel info. Please not we are using GCM and not Firebase as some of our user's devices do not support Firebase. 
 AppboyConfig.Builder appboyConfig = new AppboyConfig.Builder()
        .setDefaultNotificationChannelName("Appboy Push")
        .setDefaultNotificationChannelDescription("Appboy related push");
    Appboy.configure(this, appboyConfig.build());

**Comment by Bucimis** [comment] 2017-12-04 18:27
Hi @jazimm,

Thanks for contacting us. The Appboy default channel ID is hardcoded as `com_appboy_default_notification_channel`. See https://appboy.github.io/appboy-android-sdk/javadocs/constant-values.html#com.appboy.Constants.APPBOY_PUSH_DEFAULT_NOTIFICATION_CHANNEL_ID. The name and description set in AppboyConfig will apply to the channel belonging to this channel ID.

Note that you are not required to use the Appboy default channel.

Feel free to respond with any followups questions/thoughts.

Thanks,
Appboy Android Team

**Comment by trencoret** [comment] 2019-02-05 15:18
Hi @Bucimis 

Not sure if this comment should be here, or [here](https://github.com/Appboy/appboy-segment-android-sample) because I'm integrating Braze via Segment.

I'm unable to call setDefaultNotificationChannelName and setDefaultNotificationChannelDescription. Tried what jazimm proposed but didn't work.

```
public static void initSegment(Context context) {
        String analyticKey = Constants.getAnalyticSegmentKey();
        // Create an analytics client with the given context and Segment write key.
        Analytics analytics = new Analytics.Builder(context, analyticKey)
                // Enable this to record certain application events automatically!
                .trackApplicationLifecycleEvents()
                .trackAttributionInformation()
                //Include Braze via Segment
                .use(AppboyIntegration.FACTORY)
                .build();
        // Set the initialized instance as a globally accessible instance.
        Analytics.setSingletonInstance(analytics);
        AppboyLogger.setLogLevel(Log.VERBOSE);
        AppboyConfig.Builder appboyConfig = new AppboyConfig.Builder()
                .setDefaultNotificationChannelName("Appboy Push")
                .setDefaultNotificationChannelDescription("Appboy related push");
        Appboy.configure(context, appboyConfig.build());
```

Is it possible to set the notification channel in the appboy.xml file?

**Comment by trencoret** [comment] 2019-02-05 18:14
@Bucimis Thanks for the comment.

Do you have to set it as a string? I tried the following in appboy.xml

```
    <string name="com_appboy_default_notification_channel_name">Braze Push</string>
    <string name="com_appboy_default_notification_channel_description">Braze related push</string>
```

And it seems it's not being set correctly. I'm attaching Braze Logs for notifications:

```
02-05 15:08:41.020 10630-11759/X D/Appboy v3.0.1 .com.appboy.push.AppboyNotificationUtils: Message without notification id provided in the extras bundle received. Using a hash of the message: -1358865145
02-05 15:08:41.025 10630-11759/X D/Appboy v3.0.1 .com.appboy.push.AppboyNotificationUtils: Setting title for notification
    Setting content for notification
    Setting ticker for notification
02-05 15:08:41.034 10630-11759/X v3.0.1 .com.appboy.push.AppboyNotificationUtils: Setting delete intent.
02-05 15:08:41.041 10630-11759/X v3.0.1 .com.appboy.push.AppboyNotificationUtils: Setting small icon for notification via resource id
    Setting large icon for notification
02-05 15:08:41.957 10630-11759/X v3.0.1 .com.appboy.push.AppboyNotificationUtils: Sound key not present in notification extras. Not setting sound for notification.
    Setting summary text for notification
    Setting priority for notification
02-05 15:08:41.958 10630-11759/X D/Appboy v3.0.1 .com.appboy.push.AppboyNotificationUtils: Setting style for notification
02-05 15:08:42.521 10630-11759/X v3.0.1 .com.appboy.push.AppboyNotificationUtils: Using default accent color for notification
02-05 15:08:42.523 10630-11759/X v3.0.1 .com.appboy.push.AppboyNotificationUtils: Category not present in notification extras. Not setting category for notification.
02-05 15:08:42.525 10630-11759/X v3.0.1 .com.appboy.push.AppboyNotificationUtils: Found notification channel in extras with id: com_appboy_default_notification_channel
    Using notification channel with id: com_appboy_default_notification_channel
02-05 15:08:42.575 10630-11759/X v3.0.1 .com.appboy.push.AppboyNotificationUtils: Sending push message received broadcast
02-05 15:08:42.583 10630-11759/X D/Appboy v3.0.1 .com.appboy.push.AppboyNotificationUtils: Found notification channel in extras with id: com_appboy_default_notification_channel
```

Thanks

**Comment by radixdev** [comment] 2019-02-05 18:56
Hi @trencoret ,

Please see https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-ui/src/com/appboy/push/AppboyNotificationUtils.java#L830-L850 for the logic being used. If the notification contains a valid `NotificationChannel` (that has already been created on the device), then that channel is used. Only in the event that the notification supplied channel name is invalid OR the default notification channel has not been created do the values set in your code get used. Based on the logcat `Using notification channel with id:`, the default channel is already valid and thus won't have its fields updated.

In order to update the default notification channel name/description you'll either have to delete/reinstall the app or set those fields on the `NotificationChannel` yourself. 

I'd actually recommend just making your own `NotificationChannel` and just using that name on the dashboard. The default notification channel is only used in the above cases when the supplied notification channel is invalid or not created yet.

**Comment by trencoret** [comment] 2019-02-05 20:58
Hi @radixdev,

I was able to create another NotificationChannel different from my default one, but I still have the same issue when I send a notification from Braze, I receive the Braze notification and another notification with default settings. I just want to receive the one coming from Braze.

Not sure why Braze triggers the default one. Any ideas?

**Comment by Bucimis** [comment] 2019-02-05 21:13
@trencoret That is surprising. Each push notification should belong to only one notification channel, and double sends are not expected behavior. Could you provide more logging illustrating what's going on?

**Comment by trencoret** [comment] 2019-02-07 19:10
Hi @Bucimis @radixdev,

I was able to avoid the double sending by preventing on sending a notification with empty "message". 

I have another problem setting the importance of the notification channel. As you can see in the [docs](https://developer.android.com/reference/android/app/NotificationChannel#setImportance(int)), the importance can only be set before submitting the notification channel, and since Braze is submitting the notification channel on my behalf, I can't set the correct importance (Max/Urgent so it has the pop on screen option). 

Is there a way of setting the importance level in the appboy.xml file?

**Comment by pagrawal1407** [comment] 2019-02-27 16:26
@Bucimis I am using 'com.appboy:android-sdk-ui:2.0.5' Braze SDK in my android app. When my app was targeting android sdk 25, I was receiving push notifications on devices with API 25 and below as well as API 26 (Android O) and above. But when I change the targetsdkversion on my app to 27, I stooped receiving push notifications on devices running API 26 (Android O) and above. I still receive the notifications for older Android version devices. I am using default notification channel in my Braze campaigns. Can you help me figure out why its happening?
I also tried to create a class that implements `IAppboyNotificationFactory` and pass an instance to Appboy using `Appboy.setCustomAppboyNotificationFactory(); like you suggested above, but that was no help either.

**Comment by radixdev** [comment] 2019-02-27 16:46
@pagrawal1407 Please see my response at https://github.com/Appboy/appboy-unity-sdk/issues/33#issuecomment-467937493

**Comment by pagrawal1407** [comment] 2019-02-27 16:49
@radixdev Thanks for your reply. So I have to update my braze sdk to see those notifications?
Just to clear my doubt, what is the purpose of adding IAppboyNotificationFactory and setting the channel ID there? I thought it's can work as a workaround until I upgrade my Sdk to 2.1.0

**Comment by radixdev** [comment] 2019-02-27 17:26
@pagrawal1407 Yes you have to update your sdk to be compatible. I recommend updating to SDK 3.1.0 as well.
