### ISSUE TITLE
Custom Broadcast receiver trigger two times 

### ISSUE THREAD

**Issue by Rahulrsannidhi** [Appboy/appboy-android-sdk#94] opened 2018-04-11 07:57 UTC
In the application, we are using the custom appboy broadcast receiver and redirect the corresponding activities.While integrating the multi-colour push we did some custom style in the notification builder and works fine but when adding an image in the notification(Rich notification) first time able to get the image in the appboyExtras but broadcast receiver triggering twice the second time in the appboy extras the images map will be empty image URL is not available.

**Comment by radixdev** [comment] 2018-04-11 17:35
Hello @Rahulrsannidhi ,

A few questions.

1. What version of the Braze Android SDK are you using?
2. Can you share your `appboy.xml` file?
3. If using `AppboyConfig` configuration, can you post that code as well?
3. Can you share your AndroidManifest?
4. Can you provide steps to reproduce or a short sample project that demonstrates the issue?
5. Can you provide [verbose logcat](https://www.braze.com/documentation/Android/#verbose-logging) demonstrating your reproduction of the issue? Please force-stop the app, reproduce the issue, then send us the **_entirety_** of your app's logcat from start to finish.

**Comment by radixdev** [comment] 2018-04-12 17:27
Hello @Rahulrsannidhi , 

I'm still unsure of how to reproduce the issue. What are the intent actions received when the double trigger happens?  

If your broadcast receiver is only being used to handle push clicks, you can remove your broadcast receiver then configure the SDK to automatically handle push clicks via:

```
    AppboyConfig appboyConfig = new AppboyConfig.Builder()
        .setHandlePushDeepLinksAutomatically(true)
        .build();
    Appboy.configure(this, appboyConfig);
```

Can you share steps 5. and 6. from my original post? You can also email support@braze.com to confidentially share code/logcat output without it being on this public issue.

**Comment by radixdev** [comment] 2018-04-18 16:34
Hello @Rahulrsannidhi ,

Closing this issue since we're handling it via support.

**Closed by radixdev** 2018-04-18 16:34 UTC
