### ISSUE TITLE
Appboy SDK v10.1.3 Google Play Services

### ISSUE THREAD

**Issue by petehendryJE** [Appboy/appboy-android-sdk#45] opened 2015-11-11 14:27 UTC
Seems Appboy 10.1.3 has dependency on Google Play Services 7.8.0 which causes a build issue when app has dependency on later versions of play service e.g. >= 8.1.0. Only solution appears to be for new version of Appboy to be built to reference latest version of play services, not wishing to decrement the version of play services our app is using.

Build error: https://code.google.com/p/android/issues/detail?id=187483

**Comment by briancaw** [comment] 2015-11-11 17:15
Hi @petehendryJE 

Thanks for reporting, I can reproduce the issue.  We plan on releasing at the end of this week or early next week, so we'll try to bump our version we compile against before then (we intended to last release without knowing about this issue, but an issue with our wear support was introduced with the upgrade, so we have to iron that out first).

We'll update on the disposition of this item later this week.

Thanks,
Brian

**Comment by petehendryJE** [comment] 2015-11-12 09:12
Awesome, thanks Brian.

**Comment by briancaw** [comment] 2015-11-17 23:58
Hi @petehendryJE 

Just a heads up that this release got pushed out from early-week to mid-week, and we're planning on shipping it tomorrow.

Thanks,
Brian

**Comment by briancaw** [comment] 2015-11-20 00:48
Hi @petehendryJE 

We've just released an update that should fix this for you.  If you could confirm that this resolves your issue it'd be much appreciated.

Thanks,
Brian

**Comment by petehendryJE** [comment] 2015-11-20 15:27
Thanks Brian, will give the new version a go and let you know how I get on.

Pete

On 20 November 2015 at 00:48, briancaw <notifications@github.com> wrote:

> Hi @petehendryJE <https://github.com/petehendryJE>
>
> We've just released an update that should fix this for you. If you could
> confirm that this resolves your issue it'd be much appreciated.
>
> Thanks,
> Brian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Appboy/appboy-android-sdk/issues/45#issuecomment-158245447>
> .
>

-- 

------------------------------
This is an e-mail from the company JUST EAT plc. This e-mail may contain 
confidential information and/or privileged or personal advice. This e-mail 
is intended for the addressee(s) stated above only. If you receive this 
e-mail by mistake, please return it to JUST EAT plc without producing, 
distributing or retaining copies hereof. Thank you.

**Comment by petehendryJE** [comment] 2015-11-20 15:57
Hi Brian,

Just tested 1.11.0 in our build + works as expected, many thanks.

Regards,

Pete

On 20 November 2015 at 00:48, briancaw <notifications@github.com> wrote:

> Hi @petehendryJE <https://github.com/petehendryJE>
>
> We've just released an update that should fix this for you. If you could
> confirm that this resolves your issue it'd be much appreciated.
>
> Thanks,
> Brian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Appboy/appboy-android-sdk/issues/45#issuecomment-158245447>
> .
>

-- 

------------------------------
This is an e-mail from the company JUST EAT plc. This e-mail may contain 
confidential information and/or privileged or personal advice. This e-mail 
is intended for the addressee(s) stated above only. If you receive this 
e-mail by mistake, please return it to JUST EAT plc without producing, 
distributing or retaining copies hereof. Thank you.

**Comment by billmag** [comment] 2015-11-20 16:01
Thanks Pete, going to close this.

Cheers,
Bill

**Closed by billmag** 2015-11-20 16:01 UTC
