### ISSUE TITLE
Leaked closable objects

### ISSUE THREAD

**Issue by trauzti** [Appboy/appboy-android-sdk#39] opened 2015-04-20 13:49 UTC
My app crashes when I run it with the Appboy SDK in StrictMode with                            .detectLeakedClosableObjects()
This is the output from logcat:

+E/StrictMode(27538): A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
+E/StrictMode(27538): java.lang.Throwable: Explicit termination method 'end' not called
+E/StrictMode(27538):   at dalvik.system.CloseGuard.open(CloseGuard.java:184)
+E/StrictMode(27538):   at java.util.zip.Inflater.<init>(Inflater.java:82)
+E/StrictMode(27538):   at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:103)
+E/StrictMode(27538):   at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:88)
+E/StrictMode(27538):   at bo.app.h.a(SourceFile:72)
+E/StrictMode(27538):   at bo.app.h.a(SourceFile:52)
+E/StrictMode(27538):   at bo.app.h.a(SourceFile:43)
+E/StrictMode(27538):   at bo.app.k.a(SourceFile:36)
+E/StrictMode(27538):   at bo.app.j.a(SourceFile:36)
+E/StrictMode(27538):   at bo.app.db.run(SourceFile:64)
+E/StrictMode(27538):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
+E/StrictMode(27538):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
+E/StrictMode(27538):   at java.lang.Thread.run(Thread.java:818)

**Comment by trauzti** [comment] 2015-04-20 13:52
I decided to stop using Appboy because of this issue and moved to Fabric and Flurry instead. This is the version of Appboy I was using when I detected this issue: compile 'com.appboy:android-sdk-ui:1.6.+'

**Comment by briancaw** [comment] 2015-04-20 14:49
Hi @trauzti 

Thanks for reporting this.  We have found the cause of this error and have identified a solution that we'll test today.  We'll update with an ETA for the release of the fix this afternoon.

**Comment by trauzti** [comment] 2015-04-20 15:03
Thanks @briancaw 

Good for future users of Appboy =)

**Comment by briancaw** [comment] 2015-04-21 00:14
Hi again @trauzti 

We've got a solution tested and ready to go.  We've yet to see any signal this bug's impact is significant beyond the particular scenario you reported (which certainly isn't nothing, but  you're the only person who has reported it and you seem to be no longer blocked as you've moved away from using Appboy).  So we'll bundle this into our next planned release which will be inside of two weeks.

Thanks again for reporting this, and I hope you eventually give Appboy another try.

**Comment by trauzti** [comment] 2015-04-21 01:45
Great news @briancaw 

Excellent development speed guys. I always run my apps tracking every detail with StrictMode in the development cycle.
This issue was rather annoying because the app kept crashing after a few activities had been opened.

If I return to Appboy I hope that the app will perform well with my setup.

Best wishes,
Trausti

**Comment by briancaw** [comment] 2015-04-30 01:23
This is fixed in 1.7.2.  Thanks again @trauzti!

**Closed by briancaw** 2015-04-30 01:23 UTC
