### ISSUE TITLE
Update GCM mechanism to Firebase

### ISSUE THREAD

**Issue by yishai-glide** [Appboy/appboy-android-sdk#53] opened 2016-06-08 14:32 UTC
Since the release of FCM and the deprecation of GCM for cloud messaging, we should update token registration to be working with `FirebaseInstanceId` instead of the current method.

for more: https://developers.google.com/cloud-messaging/

**Comment by Bucimis** [comment] 2016-06-09 16:34
Hi @yishai-glide,

Thank you for contacting us.  We're actively investigating a move to FCM and are evaluating all implications for product and integration before proceeding.  We will update with  additional news on this as product decisions are made.

For the time being, our GCM integration is still supported and there is no danger of service interruptions.

Thanks,
Android Appboy Team

**Comment by yishai-glide** [comment] 2016-06-09 17:17
not sure how correct that is, we have reports of devices that no longer get pushes but we see in the logs intents coming in to appboy with `com.google.android.c2dm.intent.REGISTRATION` action

**Comment by briancaw** [comment] 2016-06-10 19:25
Hi @yishai-glide 

Can you let us know as much information as possible regarding the push failures?  Especially:

- Can you reproduce?
- Are there any error signals (e.g. our message error console, in the logcat)?
- What is the device/OS profiles have you seen the issue occur on?
- What percentage of users have you seen have this issue?

Thanks,
Brian

**Comment by briancaw** [comment] 2016-06-14 16:40
Hi @yishai-glide 

Just pinging on this - it would be great to get in front of this issue and we'd very much appreciate any info you might be able to provide.

Thanks,
Brian

**Comment by yishai-glide** [comment] 2016-06-15 09:22
here is a list of all the devices we tested on and the result

- Note 4  5.1.1
- LG Optimus F60  4.4.2
- Samsung S5 6.0.1
- Samsung Grand Prime 5.1.1
- Moto E 2nd gen  5.1
- Moto X 2nd gen  6.0
- HTC One M9  5.1
- LG G4  5.1
- Samsung S4  4.4.2
- LG Leon  5.1.1
- Nexus 6  5.1.1
- Nexus 5x  6.0.1

**Comment by briancaw** [comment] 2016-06-15 19:00
Hi @yishai-glide,

I'm not seeing the result you mention in that list - are things breaking across all of those devices?

Also, do you have any info regarding the other three questions:

- Can you reproduce? Are you saying that you can and have via those devices?  If so, what are the STR?
- Are there any error signals (e.g. our message error console, in the logcat)?
- What percentage of users have you seen have this issue?

Thanks,
Brian

**Comment by yishai-glide** [comment] 2016-06-15 20:58
Hi @briancaw sorry for the misunderstanding.

this is 100% reproducible on all these devices, there is no crash but repeated incoming intents with action `com.google.android.c2dm.intent.REGISTRATION` and `com.google.android.c2dm.intent.REGISTER` that have no actual registration after them

this version is still in internal testing and in our beta program but we haven't tested IIRC campaigns other than the one that opened this ticket.

I will try and get those numbers to you and update here ASAP

**Comment by yishai-glide** [comment] 2016-06-19 14:23
anything happening here?

**Comment by briancaw** [comment] 2016-06-19 20:21
Hi @yishai-glide 

Two things are in motion here:  1) we're actively debugging this behavior you're reporting and 2) we're strategizing around updating to FCM.

Regarding #1, we have a few more questions:

- Did this behavior emerge from an application that was working with Appboy's GCM push solution?  i.e. did you have registrations working and then they stopped?  Any idea what might have changed?
- Re: changes, specifically have you modified any sort of handling regarding GCM/FCM?
- Are you able to debug what's happening in our GCM reciever when the `REGISTRATION` intent is fired?  That should cause our receiver to call https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-ui/src/com/appboy/AppboyGcmReceiver.java#L54...can you let us know if that call is successfully reaching https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-ui/src/com/appboy/AppboyGcmReceiver.java#L78, and if so if the value passed as a registration ID looks valid?

We'll continue investigating this with high urgency; we'll report updates/findings ASAP.

Thanks,
Brian

**Comment by yishai-glide** [comment] 2016-06-20 09:18
hi @briancaw I successfully got to https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-ui/src/com/appboy/AppboyGcmReceiver.java#L78 without any issues and the token seems to be a real one.

When I internally request one via FirebaseInstanceId, I get a different token and when sending a push notification campaign it seems like it's not sending out anything.

I tried adding this line in my own FCM registration service but it didn't fix the issue
```
String registrationId = FirebaseInstanceId.getInstance().getToken(SENDER_ID, FirebaseMessaging.INSTANCE_ID_SCOPE);
Appboy.getInstance(applicationContext).registerAppboyPushMessages(registrationId);
```

**Comment by briancaw** [comment] 2016-06-20 15:48
Hi @yishai-glide 

Thanks for that debugging information.  We have a few followup questions, but I think we're getting closer to the root of the issue:

- In the normal use case, are you calling `registerAppboyPushMessages` with a FirebaseInstanceId?  Or are you letting our GCMReceiver do automatic registration?  Or both (which would be a bug)?  If you are already registering for push in your app you should disable our registration by setting https://github.com/Appboy/appboy-android-sdk/blob/master/droidboy/res/values/appboy.xml#L23 to false and setting the registrationId manually.  
- In any case it sounds like you've confirmed that `registerAppboyPushMessages` is being called; but you've also said that users aren't being registered.  That method call with a registrationId it should result in a registered user; are you not seeing that?  
- If users are registering but pushes are failing, are you seeing errors in your Message Error Console?  
- If sends are failing, have you modified your GCM API key in Appboy, or any other aspect of your GCM credentials?

Thanks,
Brian

**Comment by yishai-glide** [comment] 2016-06-20 16:49
- in our current code base we never call `registerAppboyPushMessages` and always let AppboyGcmReceiverer do the work and we always had our appboy.xml file with `<bool name="com_appboy_push_gcm_messaging_registration_enabled">true</bool>`.
- I tried calling it as a check and it made no difference 
- from what I understand from our QA and from what I saw, the messages aren't being sent even though segments have users that are push enabled
- we have not modified any of our registrationIds but from my understanding by correspondence with google people is that there is a fundamental change between the structure of a FCM key and a GCM key.

**Comment by briancaw** [comment] 2016-06-20 16:56
Hi @yishai-glide,

At this point, I think it makes sense for us to debug this with your team as a support ticket; we an update this issue with the final disposition of that investigation.  Existing GCM solutions should still work and we'll want to identify why, for example, messages aren't being sent (which is very different from messages being sent and failing, which would be more in-line with a possible authentication/key-change error).

Thanks,
Brian

**Comment by briancaw** [comment] 2016-06-20 19:09
Per offline investigation, this was caused by upgrading to FCM for a parallel registration path, part of with included removing the C2D_MESSAGE permission, which caused the error.

Leaving this issue open as the initial issue is still open - i.e. we do plan on updating to FCM in the near future and will close this out when we do.

**Comment by jonschmidt** [comment] 2016-06-21 10:26
Just to clarify, upgrading to FCM *will* break AppBoy notifications until you have implemented support officially? Or it will work, as long as we keep c2dm permissions intact and handle registration manually? We need to upgrade to FCM for our internal purposes but it seems we might be blocked by this.

**Comment by briancaw** [comment] 2016-06-21 21:05
Hi @jonschmidt 

Previously our recommended support for side by side GCM support was as follows:  one service registered for push and passes values to others, one routing receiver listens to push and routes them based on payload content (e.g. if the payload has the pApboy key in it, spin up AppboyGcmReceiver and call onReceive with appropriate values).  Can you verify if this is similar to your configuration? If not, can you give us some information regarding your setup?

We're currently testing a similar implementation with FCM/GCM side-by-side and should have updates in the next day or two regarding an analogous solution as a supported/working side-by-side integration; if that solution doesn't work, we'll update on either a different solution or our plan moving forward.  As of right now  we haven't had a confirmation that things are working or are not working in that recommended configuration with Appboy/FCM side-by-side.

Thanks,
Brian

**Comment by jonschmidt** [comment] 2016-06-22 10:02
@briancaw currently we handle our own token registration for GCM, then pass it to appBoy via the `handleRegistration` method. We let AppBoy handle it's own messages via the `AppboyGcmReceiver`. In our own receiver, we just ignore anything that does not come from us. This seems to work fine, and I could also see it working with Firebase, as long as the tokens between GCM and FCM are interchangeable. I haven't looked into this yet.

**Comment by briancaw** [comment] 2016-06-23 16:44
Hey All,

We can confirm that FCM/Appboy work side-by-side.  The recommended implementation is closer to your existing one @jonschmidt (which was the suggested implementation for folks who had full control of that first receiver and could ensure it wouldn't act on Appboy messages). 

```
1) Register with Firebase instead of Appboy, as Firebase registers automatically.  Turn off Appboy automatic registration by setting `com_appboy_push_gcm_messaging_registration_enabled` to false.

2) Send Appboy your Firebase Token:

Appboy.getInstance(this).registerAppboyPushMessages(FirebaseInstanceId.getInstance().getToken("<your-sender-id>", "FCM"));

3) Appboy and Firebase pushes should now work as normal.  Appboy's BroadcastReceiver will ignore non-Appboy push received Intents.

4) No manifest changes are necessary.
```

Please let us know any further comments or questions.

Thanks,
Brian

**Comment by yishai-glide** [comment] 2016-06-23 16:50
will this still allow host applications to handle incoming pushes if needed?

**Comment by briancaw** [comment] 2016-06-23 16:57
Hey @yishai-glide 

Can you elaborate on/clarify that question? Having a bit of trouble figuring out exactly which functionality your asking about.

Thanks,
Brian

**Comment by yishai-glide** [comment] 2016-06-23 18:08
please ignore, I was thinking of something else, it seems to be working for now, waiting for our QA team to resolve the ticket.
leaving this ticket open to allow your systems to be updated

**Comment by yishai-glide** [comment] 2016-06-27 17:19
Our internal ticket for this was closed, meaning we confirmed that this solution works for now

**Comment by nlindroos** [comment] 2016-08-30 09:48
Hi @briancaw 

I have set up my project with Appboy and FCM integrations according to the instructions [in your earlier post](https://github.com/Appboy/appboy-android-sdk/issues/53#issuecomment-228110261). Having problems with registering the generated push tokens with Appboy though. I'm sending the tokens using
`            Appboy.getInstance(this.mContext).registerAppboyPushMessages(FirebaseInstanceId.getInstance().getToken("38XXXXXXXXXX", "FCM"));
`.

I've verified that the sent tokens are correct. The problem is that the success rate of registering these tokens in Appboy is not 100 %. I.e. the tokens do not reliably get associated with a user and are not visible in the user search. Executing `registerAppboyPushMessages` does not result in any kind of error and does indeed seem to occasionally work. Haven't been able to pin down the difference in scenarios where it does/doesn't work.

Any ideas? Cheers,
Niklas

**Comment by Bucimis** [comment] 2016-08-30 15:34
Hey @nlindroos

Thanks for reporting this issue.

1) Where in your app are you calling `registerAppboyPushMessages()`?  e.g. inside your `FirebaseInstanceIdService`, in a specific activity, etc.  This may have an effect on when/how often the push token is registered with Appboy. Does it get called for all users, or only if they perform a specific action?

2) What percentage of users are affected and is there a correlation with any user characteristic (e.g. device type, API level, num sessions, etc)?

3) Do you have automatic data flush turned off? Is there an improvement if you call `requestImmediateDataFlush()` immediately after calling `registerAppboyPushMessages()`?

Thanks for helping us debug,
Appboy Android Team

**Comment by briancaw** [comment] 2016-09-10 17:34
Hi All,

We've officially updated our SDK and documentation to reflect our recommended FCM integration.  You can see our documentation for this here: https://www.appboy.com/documentation/Android/#push-notifications.

Please feel free to update or re-open this issue if you have any further comments or questions, and thanks everyone for reporting information regarding this issue.

**Closed by briancaw** 2016-09-10 17:34 UTC

**Comment by sathish25** [comment] 2016-09-13 03:07
Hi All,

I am integrating Appboy now, the documentation shows how to integrate FCM, but there is no proper example to handle push from Appboy. Currently all Appboy push messages are received in onMessageReceived(RemoteMessage remoteMessage) of FirebaseMessagingService, then how I can pass to Appboy to handle the push notification? In case of GCM the Appboy example shows that the BroadcastReceiver sends to AppboyNotificationUtils.routeUserWithNotificationOpenedIntent(context, intent);

Also I have implemented this in my application class: Appboy.setCustomAppboyNotificationFactory(new DroidboyNotificationFactory());

Actually my app is going to handle push messages as well as deep linking from Appboy.
Also push messages from ZenDesk.

Please guide me to integrate FCM with Appboy. I have the latest Appboy example project.

Thanks

**Comment by briancaw** [comment] 2016-09-13 19:56
Hello @sathish25 

We have not observed FCM intercepting/blocking push messages sent from Appboy (or have had any reports of that behavior).  Can you confirm that what you have tested is behavior where a push sent from Appboy is not reaching our GCM receiver?

Can you let us know how you've declared our `AppboyGCMReceiver` in your AndroidManifest?

Thanks,
Brian

**Comment by sathish25** [comment] 2016-09-13 22:43
Hi @briancaw ,

I think you didn't understand my question properly. I didn't say that FCM is blocking the push message.

Why should I implement AppboyGCMReceiver when FCM is in place?
Hope Appboy doesn't need GCM implementation when FCM is integrated. 

When FCM is integrated then all push messages will be received in the following class which is working absolutely fine.

public class MyAppFcmListenerService extends FirebaseMessagingService {

    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
    }
}

As per your documentation to handle custom push messages then to create BroadcastReceiver to handle the same. So I followed it and created the custom Broadcast receiver which is not receiving Appboy message instead all Appboy push messages are received in the above method onMessageReceived()

<receiver android:name="YOUR-BROADCASTRECEIVER-NAME" android:exported="false" >
  <intent-filter>
    
    <action android:name="YOUR-APPLICATION-PACKAGE-NAME.intent.APPBOY_PUSH_RECEIVED" />
    <action android:name="YOUR-APPLICATION-PACKAGE-NAME.intent.APPBOY_NOTIFICATION_OPENED" />
  </intent-filter>
</receiver>


The documentation and your example project is mainly for GCM integration, but there is not much for FCM.

**Comment by briancaw** [comment] 2016-09-14 21:10
Hi @sathish25 

`AppboyGCMReceiver` is still functional with the FCM setup we outline in our documentation and it is how we instrument push. We plan on renaming it in the future to `AppboyFCMReceiver`.  Do you have that integrated in your AndroidManifest as we describe in our documentation (your comment leads me to thinking you don't have it integrated)?  If not, please integrate it as outlined in our documentation.

Thanks in advance for this information,
Brian

**Comment by sathish25** [comment] 2016-09-15 00:24
Hi @briancaw ,

Yes, I didn't add AppboyGcmReceiver in manifest.xml, because I thought which is not part of FCM. Also there is no information to add this while integrating with FCM/GCM.

I am not upgrading Appboy from GCM to FCM, this is the first time I am integrating Appboy with my app which is already upgraded to FCM. So I am always thinking of FCM while integrating Appboy.

Main confusing part is the file name "AppboyGcmReceiver", next the receiver in the manifest  with "com.google.android.c2dm.intent.RECEIVE", as per FCM all "com.google.android.c2dm...." has to be removed.

Please update your documentation accordingly to avoid confusion.

Thanks

**Comment by briancaw** [comment] 2016-09-15 15:17
Hi @sathish25 

Please reference our `Displaying Push` documentation for how to integrate the `AppboyGCMReceiver`.  We'll add a note to the beginning of that session to make more clear that it applies to both FCM and GCM setup.

Thanks,
Brian

**Comment by sathish25** [comment] 2016-09-16 03:39
Hi @briancaw 

Thanks for your support.

Regards,
Sathish
