### ISSUE TITLE
[Bug]: com.appboy.Appboy.<init> error 

### ISSUE THREAD

**Issue by henna59** [Appboy/appboy-android-sdk#265] opened 2024-02-06 09:00 UTC
### Braze Android SDK Version

15.0.0

### Steps To Reproduce

I received the error report from Firabasecrashlytics. 
There's no specific reduction process.
My app initializes braze in the application lifecycle.
User just used app. 

### Expected Behavior

.

### Actual Incorrect Behavior

.

### Verbose Logs

```shell
Fatal Exception: java.lang.OutOfMemoryError
pthread_create (1040KB stack) failed: Try again
java.lang.Thread.nativeCreate (Thread.java)
java.lang.Thread.start (Thread.java:976)
java.util.concurrent.ThreadPoolExecutor.addWorker (ThreadPoolExecutor.java:954)
java.util.concurrent.ThreadPoolExecutor.execute (ThreadPoolExecutor.java:1362)
com.appboy.Appboy.<init> (Unknown Source:71)
com.braze.Braze.<init> (SourceFile:1)
com.appboy.Appboy.getInstance (Unknown Source:7)
com.braze.Braze.getInstance (SourceFile:1)
com.braze.BrazeActivityLifecycleCallbackListener.onActivityStopped (BrazeActivityLifecycleCallbackListener.java:146)
android.app.Application.dispatchActivityStopped (Application.java:510)
android.app.Activity.dispatchActivityStopped (Activity.java:1582)
android.app.Activity.onStop (Activity.java:2772)
androidx.fragment.app.FragmentActivity.onStop (FragmentActivity.java:369)
androidx.appcompat.app.AppCompatActivity.onStop (AppCompatActivity.java:257)
android.app.Instrumentation.callActivityOnStop (Instrumentation.java:1623)
android.app.Activity.performStop (Activity.java:9198)
android.app.ActivityThread.callActivityOnStop (ActivityThread.java:5897)
android.app.ActivityThread.performStopActivityInner (ActivityThread.java:5871)
android.app.ActivityThread.handleStopActivity (ActivityThread.java:5942)
android.app.servertransaction.TransactionExecutor.performLifecycleSequence (TransactionExecutor.java:240)
android.app.servertransaction.TransactionExecutor.cycleToPath (TransactionExecutor.java:205)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:177)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:98)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2685)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loopOnce (Looper.java:230)
android.os.Looper.loop (Looper.java:319)
android.app.ActivityThread.main (ActivityThread.java:8893)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:608)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1103)
```

**Comment by radixdev** [comment] 2024-02-06 16:22
Hi @henna59 ,

Please update your SDK version to a more recent one. We've made many threading updates since 15.0.0 that should help with your OOM.

**Comment by bryanlogan** [comment] 2024-02-06 16:25
A few things I'm seeing here:

1) This is an OutOfMemoryError error. That doesn't necessarily indicate an issue with our SDK, simply that we were the code running when the memory ran out. You may want to investigate to see if there's a memory leak anywhere within your app.
2) This is crashing on an initialization that's occurring as a result of "getInstance".  While we do initialize the singleton on the first get, this first get shouldn't have occurred during the Activity's onStop, but it should've been invoked as part of the "onStart". So there's something going on there, but it's hard to tell without the logs.
3) version 15.0.0 is 2.5 years old now. Please update to the latest version (now found at https://github.com/braze-inc/braze-android-sdk/)

Given the above, I'm going to close this issue. If you're able to reproduce, reach out to Braze support and we can look into it.

**Closed as completed by bryanlogan** 2024-02-06 16:25 UTC
Labels: bug
